from enum import Enum

class MessageTypes(Enum):
#Anything
    BROAD = "BRD"
    
#Authenication
    LOGIN = "LOGIN"
    USER_SIGNUP = "USERSIGNUP"
    FREELANCER_SIGNUP ="FRLNCSIGNUP"
    VERIFICATION = 'VERIFYING'
    FORGOT_PASSWORD_REQUEST = "FRGT_PAS_RQT"
    FORGOT_PASSWORD_AUTHENTICATION = "FRGT_PASS_AUTH"
    CHANGE_PASS = "CHNG_PAS"

#Homepage
    GET_USER_INFO = "USR_INFO"
    GET_PUBLIC_PROFILE_INFO= "PBL_INFO"


class StatusMessage(Enum):
#Anything
    TOKEN_BAD = "BAD_TKN"
    
#Authenication
    LOGGED_IN = "LOGGED"
    FAILED_LOG_IN = "FAILED_LOG"
    
    SIGNING_UP = "SIGNED"
    FAILED_SIGN_UP = "FAILED_SIGNED" 
    
    VERIFICATION_GOOD = "VERI_GOOD"
    VERIFICATION_BAD = "VERI_BAD"
    
    FORGOT_PASSWORD_GOOD = "FRGT_GOOD"
    FORGOT_PASSWORD_BAD = "FRGT_BAD"
    
    CHANGE_PASSWORD_GOOD = "CHNG_GOOD"
    CHANGE_PASSWORD_BAD = "CHNG_BAD"
    
#Homepage
    GOT_USER_INFO = "GOT_USR_INFO"
    FAILED_TO_GET_USER_INFO = "FLD_USR_INFO"
    