export const MessageTypes = Object.freeze({
  LOGIN_REQUEST: 'LOGIN_REQ',
  LOGIN_RESPONSE: 'LOGIN_RES',
  
  USER_INFO: 'USRINFO',
  GET_APPOINTMENTS: 'GETAPPOINT',
  NEW_APPOINTMENT_USER_RECEIVED: 'UPDATE_APPOINT_USER',
  NEW_APPOINTMENT_FREELANCER_RECEIVED: 'UPDATE_APPOINT_FREELANCER',
  REMOVED_APPOINTMENT_USER: 'APPOINT_REMOVED_USER',
  REMOVED_APPOINTMENT_FREELANCER: 'APPOINT_REMOVED_FREELANCER',
  PROFESSIONAL_LIST: 'PRO_LIST',
  PROFESSIONAL_FILTER: 'PRO_FILTER',
});

