export const MessageTypes = Object.freeze({
//Anything
  BROAD:"BRD",

//Authentication
  LOGIN: "LOGIN",
  USER_SIGNUP: "USERSIGNUP",
  FREELANCER_SIGNUP:"FRLNCSIGNUP",
  VERIFICATION:"VERIFYING",
  FORGOT_PASSWORD_REQUEST:"FRGT_PAS_RQT",
  FORGOT_PASSWORD_AUTHENTICATION:"FRGT_PASS_AUTH",
  CHANGE_PASS: "CHNG_PAS",

//Homepage
    GET_USER_INFO: "USR_INFO",
    GET_PUBLIC_PROFILE_INFO: "PBL_INFO",
    UPDATE_APPOINTMENTS_STATUS: "UPDT_APP_STAT",
    MARK_READ_NOTIFICATION: "RD_NTFC",
    MAKE_APPOINTMENT:"MK_APP",

});


export const StatusMessage = Object.freeze({
//Anything
    TOKEN_BAD:"BAD_TKN",
  
//Authentication
    LOGGED_IN: "LOGGED",
    FAILED_LOG_IN: "FAILED_LOG",

    SIGNING_UP: "SIGNED",
    FAILED_SIGN_UP: "FAILED_SIGNED",

    VERIFICATION_GOOD:"VERI_GOOD",
    VERIFICATION_BAD:"VERI_BAD",

    FORGOT_PASSWORD_GOOD:"FRGT_GOOD",
    FORGOT_PASSWORD_BAD:"FRGT_BAD",
    
    CHANGE_PASSWORD_GOOD: "CHNG_GOOD",
    CHANGE_PASSWORD_BAD: "CHNG_BAD",
  
//Homepage
    GOT_USER_INFO: "GOT_USR_INFO",
    FAILED_TO_GET_USER_INFO: "FLD_USR_INFO",

    UPDATED_APP_STATUS:"UPDT_APP",
    FAILED_TO_UPDATE_APP_STATUS:"FAILED_UPDT_APP",
    
    MARKED_READ_NOTIFICATIONS: "READ_NOTIFICATIONS",
    FAILED_TO_MARK_READ_NOTIFICATIONS: "FAILED_READ_NOTIFICATIONS",

    BOOKED_APPOINTMENT:"BKD_APP",
    FAILED_TO_BOOK_APPOINTMENT:"FLD_BKD_APP",
})

